# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Moda by Flora
email: flora@modabyflora.com
description: > # this means to ignore newlines until "baseurl:"
  Vêtements femme, enfants et homme de haute couture de Paris à prix défiant toute concurrence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://modabyflora.com" # the base hostname & protocol for your site, e.g. http://example.com

# Include the _pages folder
include: ["_pages", "_data"]

# Company Information
company_name: Moda by Flora
address_line: Quartier Attiegou Togo 2000, BP 8005, Lomé, Togo
telephone_number: +228 90 21 60 53
fax_number: +228 90 21 60 53
company_email: flora@modabyflora.com
google_map: https://www.google.tg/maps/place/6%C2%B011'28.7%22N+1%C2%B015'15.9%22E/@6.191292,1.2538618,19z/data=!3m1!4b1!4m14!1m7!3m6!1s0x1023e1c113185419:0x3224b5422caf411d!2zTG9tw6ksIFRvZ28!3b1!8m2!3d6.1256261!4d1.2254183!3m5!1s0x0:0x0!7e2!8m2!3d6.1912921!4d1.2544087



# Social Link
facebook_link: http://www.facebook.com/modabyflora
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
